// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
const databaseUrl = process.env.DATABASE_URL as string;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set");
}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
};
